version: "3"

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php ./bin/console rr-messenger:worker"
    relay: pipes

amqp:
    addr: amqp://guest:guest@rabbitmq:5672

jobs:
    pool:
        num_workers: 1
        debug: true
    consume: [ "test" ]
    pipelines:
        test:
            driver: amqp
            config:
                prefetch: 1
                consume_all: true
                durable: true
                exchange_durable: true
                queue: test-queue
                exchange: test-exchange
                exchange_type: direct
                routing_key: test
                requeue_on_fail: true

logs:
    level: debug
    mode: development